language: python
python:
  - "3.7"
#
#before_install:
#  - poetry export --output requirements.txt
#  - pip install -r requirements.txt
#
#install:
#  - pip install .

script: coverage run -m unittest discover tests
after_script: coveralls
