language: python
python:
  - "3.7"
#
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - poetry export --without-hashing --output requirements.txt
  - pip install -r requirements.txt
#
#install:
#  - pip install .

script: coverage run -m unittest discover tests
after_script: coveralls
