language: python
python:
  - "3.8"
#
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
#install:
install:
  - pip install .

script: coverage run -m unittest discover tests
after_script: coveralls
