[tool.poetry]
name = "skaworkflows"
version = "0.1.9"
description = "Generate workflows for simulating SKA Science Data Processor performance"
authors = ["Ryan Bunney"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy  = "^1.20.0"
pandas =  "^1.3.0"
networkx = "^2.6"
matplotlib = "^3.1.1"
sdp-par-model = { git = "https://github.com/ska-telescope/sdp-par-model.git" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
