name: Python package

on:
  push:
    branches:
      - master  #  Only run on pushes to master
  pull_request:
    types: [opened, synchronize]  # Run on PRs from any branch

jobs:
  unittests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      - name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel coveralls pytest pytest-cov
      - name: Install skaworkflows
        run: |
          pip install .
      - name: Run unittests with coverage
        run: |
          pytest . --cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
